### PR TITLE
Number base conversion

### PR DESCRIPTION
**Pull request by savvasth96**
binary to decimal vice versa

### CODE REVIEW

**Comment by fwcd** [comment]
Thanks for your contribution, nice idea!

We could probably combine these into a single function taking a number from base n to base k though. Also, these kinds of conversions generally belong into `ExtMath` (so as to not clutter the codebase with lots of static utility classes).

**Comment by savvasth96** [comment]
> Thanks for your contribution, nice idea!
> 
> We could probably combine these into a single function taking a number from base n to base k though. Also, these kinds of conversions generally belong into `ExtMath` (so as to not clutter the codebase with lots of static utility classes).

Thank you glad you liked it!
Yeah that would be better. I'm thinking it would be best if it supports only the main ones (decimal, binary, octal, hexadecimal). I will update it in the upcoming days!

**Comment by fwcd** [comment]
Note that similar methods already exist:

`Integer.toString(n, radix)`
`Integer.parse(s, radix)`

These can encode and decode numbers from and into arbitrary bases and should, in addition to the standard Java literals (`0x` for hexadecimal, `0` for octal, `0b` for binary), cover most use cases in practice.

_However_, there might be another scenario where such a utility could be useful: Representing base-n numbers as base-10 numbers, e.g. a function that converts `0b1011` to `1011` or `0x92` into `92`. Note that not all hexadecimal numbers have such a representation (precisely those that include 'letters').

Since there is a pretty simple algorithm for extracting the digits of a number (repeatedly perform integer division with remainder), there is no need to hardcode certain bases. Instead of  `binary`, `octal`, `hexadecimal`, the user would just pass `2`, `8` or `16` into the function.

**Comment by savvasth96** [comment]
I updated it to support decimal, binary, octal, hexadecimal. Basically uses the built-in Integer functions you mentioned.

**Pull request merged**
